trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'DEV'
  jobs:
  - job: DevDeploy
    displayName: Deploy to DEV
    steps:
    - template: provision.yml
      parameters: 
        location: uksouth
        env: dev

- stage: 'UAT'
  jobs:
  - job: DevDeploy
    displayName: Deploy to UAT
    steps:
    - template: provision.yml
      parameters: 
        location: uksouth
        env: uat        