trigger:
  - ci-cd/initial-pipeline

pool:
  vmImage: ubuntu-latest

variables:
  tagPlatform: 'Moo Integration'
  tagSubPlatform: 'Integration'
  tagDataClassification: 'moo-confidential'
  tagBusinessCriticality: 'business-supporting'
  tagPcode: 'P_000404'
  tagTeam: 'Gang of Moos'

stages:
- stage: 'DEV_EUN'
  jobs:
  - job: DevDeploy
    displayName: Deploy to DEV
    variables:
      tagStage: 'Dev'
      location: 'northeurope'
      resourceGroupName: 'Moo-RG-$(tagStage)'
    steps:
    - task: AzureCLI@2
      displayName: Provision resources
      inputs:
        azureSubscription: 'Visual Studio Premium with MSDN (8b113cd9-0ac3-43c9-868a-6d4334e796b7)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create \
          --name $(resourceGroupName) \
          --location $(location) \
          --tags platform='$(tagPlatform)' \
            sub-platform='$(tagSubPlatform)' \
            stage=$(tagStage) \
            data-classification=$(tagDataClassification) \
            business-criticality=$(tagBusinessCriticality) \
            pcode=$(tagPcode) \
            team=$(tagTeam)
