trigger:
- align

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'DEV'
  jobs:
  - job: DevDeploy
    displayName: Deploy to DEV
    steps:
    - template: provision.yml
      parameters: 
        location: uksouth
        env: dev