trigger:
  - ci-cd/initial-pipeline

pool:
  vmImage: ubuntu-latest

variables:
  sctNonProdSubName: SCTIntegrationNonProd
  sctProdSubName: SCTIntegrationProd

stages:
- stage: 'DEV_EUN'
  jobs:
  - job: DevDeploy
    displayName: Deploy to DEV
    variables:
      tagStage: 'Dev'
      location: 'northeurope'
    steps:
    - template: provision.yml
      parameters:
        subscriptionName: $(sctNonProdSubName)
        location: $(location)
        stage: $(tagStage)
